#!/usr/bin/env python3
"""Workflow for personal-non-auto-insurance-agent — generated by Workflow Designer Agent.

Agent orchestration: profile-modeler → policy-orchestrator → gap-diagnosis-engine → churn-recovery-agent
Closed-loop: churn-recovery-agent can re-trigger gap-diagnosis-engine via gap-reactivation strategy.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from src.agent_framework import AgentRunner, AgentOutputManager, CausalInferencePipeline

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_GROUP_DIR = Path(__file__).parent
_AGENTS_DIR = _GROUP_DIR / "agents"
_OUTPUT_BASE = _GROUP_DIR / "output"  # per-agent intermediate outputs
_DATA_DIR = _GROUP_DIR / "data"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_agent_prompt(agent_name: str) -> str:
    """Load a custom agent prompt from the group's agents/ directory."""
    path = _AGENTS_DIR / f"{agent_name}.md"
    if not path.exists():
        available = [f.stem for f in _AGENTS_DIR.glob("*.md")]
        raise FileNotFoundError(
            f"Agent prompt not found: {path}\nAvailable: {available}"
        )
    return path.read_text(encoding="utf-8")


def _now_iso() -> str:
    return datetime.now().strftime("%Y-%m-%dT%H:%M:%S")


# ---------------------------------------------------------------------------
# WorkflowRunner
# ---------------------------------------------------------------------------


class WorkflowRunner:
    """Orchestrate the 4-agent closed-loop workflow for personal non-auto insurance.

    Execution order:
      1. profile-modeler      — build multi-dimensional user profile
      2. policy-orchestrator   — policy lifecycle management & monitoring
      3. gap-diagnosis-engine  — gap diagnosis, causal calibration, plan generation
      4. churn-recovery-agent  — churn detection, causal attribution, recovery
      5. (optional feedback)   — churn triggers gap-reactivation → re-run step 3
    """

    def __init__(
        self,
        data_path: str | None = None,
        prompt: str | None = None,
        client: Any = None,
        model: str = "deepseek-v4-pro",
        output_dir: str = "./output",
    ) -> None:
        self.data_path = data_path
        self.prompt = prompt or "执行个人非车险智能体全流程分析"
        self.client = client
        self.model = model
        self.output_dir = output_dir

        self.results: dict[str, Any] = {}
        self._output_mgr = AgentOutputManager(_OUTPUT_BASE)

        # Ensure data directories exist
        for sub in ["profiles", "policies", "events", "reports", "recovery",
                     "causal_inputs", "causal_outputs/gap_calibration",
                     "causal_outputs/churn_attribution", "causal_outputs/strategy_evaluation"]:
            (_DATA_DIR / sub).mkdir(parents=True, exist_ok=True)

    # -----------------------------------------------------------------------
    # Public API
    # -----------------------------------------------------------------------

    def run(self) -> dict[str, Any]:
        """Execute the full workflow and return structured results."""
        print("\n" + "=" * 60)
        print("  个人非车险智能体工作流")
        print("  profile-modeler → policy-orchestrator → gap-diagnosis-engine → churn-recovery-agent")
        print("=" * 60)
        print(f"  启动时间: {_now_iso()}")
        print(f"  数据路径: {self.data_path or '(模拟数据)'}")
        print(f"  用户需求: {self.prompt[:120]}{'...' if len(self.prompt) > 120 else ''}")
        print(f"  模型: {self.model}")
        print(f"  主输出目录: {self.output_dir}")
        print(f"  中间输出目录: {_OUTPUT_BASE}")

        try:
            # ---------------------------------------------------------------
            # Step 1: profile-modeler — 用户画像建模
            # ---------------------------------------------------------------
            self._step_profile_modeler()

            # ---------------------------------------------------------------
            # Step 2: policy-orchestrator — 保单全生命周期管理
            # ---------------------------------------------------------------
            self._step_policy_orchestrator()

            # ---------------------------------------------------------------
            # Steps 3-5: gap-diagnosis-engine — 保障缺口诊断
            #   Step 3: 社保商保比对 + 缺口量化
            #   Step 4: 因果推断校准
            #   Step 5: 三档方案生成
            # ---------------------------------------------------------------
            self._step_gap_diagnosis_engine()

            # ---------------------------------------------------------------
            # Steps 6-8: churn-recovery-agent — 流失召回
            #   Step 6: 监听保单异常 → 流失判定
            #   Step 7: 因果归因分析
            #   Step 8: 差异化召回策略执行
            # ---------------------------------------------------------------
            self._step_churn_recovery_agent()

            # ---------------------------------------------------------------
            # Feedback loop: churn → gap reactivation
            # ---------------------------------------------------------------
            if self._should_trigger_gap_reactivation():
                print("\n" + "─" * 50)
                print("[反馈闭环] 流失召回触发了缺口再触达，重新执行缺口诊断...")
                print("─" * 50)
                self._step_gap_diagnosis_engine(reactivation_mode=True)

        except Exception as e:
            print(f"\n[ERROR] 工作流执行异常: {e}")
            import traceback
            traceback.print_exc()
            self.results["workflow_error"] = str(e)

        # ---------------------------------------------------------------
        # Final summary
        # ---------------------------------------------------------------
        print("\n" + "=" * 60)
        print("  工作流执行完毕")
        print(f"  完成时间: {_now_iso()}")
        print(f"  已执行步骤: {[k for k in self.results if not k.startswith('_')]}")
        print("=" * 60)

        # Save workflow summary
        summary = {
            "workflow": "personal-non-auto-insurance-agent",
            "completed_at": _now_iso(),
            "steps_executed": list(self.results.keys()),
            "causal_analyses_run": self.results.get("_causal_runs", []),
        }
        self._output_mgr.save_output(
            "__workflow__", "workflow_summary.json",
            json.dumps(summary, ensure_ascii=False, indent=2),
            description="工作流执行汇总",
        )

        return self.results

    # -----------------------------------------------------------------------
    # Step 1: profile-modeler
    # -----------------------------------------------------------------------

    def _step_profile_modeler(self) -> None:
        """Step 1: 采集多维数据，构建用户画像与标签体系。"""
        print("\n" + "─" * 50)
        print("[Step 1/4] profile-modeler — 用户画像建模")
        print("─" * 50)

        prompt = _load_agent_prompt("profile-modeler")
        agent = AgentRunner(prompt, self.client, model=self.model)

        message = f"""请为用户构建全维度画像。

**上下文信息**:
- 数据路径: {self.data_path or '使用内置模拟数据'}
- 用户需求: {self.prompt}
- 画像输出目录: {_DATA_DIR / 'profiles'}
- 当前时间: {_now_iso()}

请执行以下操作:
1. 从数据源采集基础信息、保单数据、健康数据、行为日志
2. 生成基础标签、保障标签、健康标签、行为标签
3. 基于规则引擎推断需求标签（医疗刚需、大病保障、家庭责任、养老储蓄、子女规划、出行保障）
4. 将结构化画像JSON保存到 data/profiles/ 目录
5. 输出画像概要（需求标签列表及其置信度）

完成后请输出画像核心结论。"""

        result = agent.run(message)
        self.results["profile_modeler"] = result
        self._output_mgr.save_output(
            "profile-modeler", "profile_result.txt", result,
            description="用户画像建模完整输出（基础/保障/健康/行为/需求五维标签）",
        )
        print(f"  [Step 1] profile-modeler 完成")

    # -----------------------------------------------------------------------
    # Step 2: policy-orchestrator
    # -----------------------------------------------------------------------

    def _step_policy_orchestrator(self) -> None:
        """Step 2: 建立家庭保单台账，启动巡检与状态机。"""
        print("\n" + "─" * 50)
        print("[Step 2/4] policy-orchestrator — 保单全生命周期管理")
        print("─" * 50)

        # Provide upstream context via two-step lookup
        upstream_ctx = self._output_mgr.format_context_for_agent()

        prompt = _load_agent_prompt("policy-orchestrator")
        agent = AgentRunner(prompt, self.client, model=self.model)

        message = f"""{upstream_ctx}

请基于上游 profile-modeler 的用户画像数据，执行保单全生命周期管理。

**上下文信息**:
- 用户需求: {self.prompt}
- 保单状态输出目录: {_DATA_DIR / 'policies'}
- 预警事件输出目录: {_DATA_DIR / 'events'}
- 家庭报告输出目录: {_DATA_DIR / 'reports'}
- 当前时间: {_now_iso()}

请执行以下操作:
1. 从画像数据中读取 insurance_tags，建立家庭保单台账，按被保人分组
2. 执行到期预警巡检（短期险T-30/15/7分级预警）
3. 执行缴费状态检查（宽限期预警、失效检测）
4. 生成家庭保障汇总报告
5. 维护保单全生命周期状态机
6. 将异常保单事件（失效/到期未续/退保）写入事件队列供 churn-recovery-agent 消费

完成后请输出保单管理摘要和预警事件清单。"""

        result = agent.run(message)
        self.results["policy_orchestrator"] = result
        self._output_mgr.save_output(
            "policy-orchestrator", "policy_status.txt", result,
            description="保单全生命周期管理输出（保单台账/到期预警/缴费状态/家庭报告/状态机事件）",
        )
        print(f"  [Step 2] policy-orchestrator 完成")

    # -----------------------------------------------------------------------
    # Steps 3-5: gap-diagnosis-engine
    # -----------------------------------------------------------------------

    def _step_gap_diagnosis_engine(self, reactivation_mode: bool = False) -> None:
        """Steps 3-5: 保障缺口诊断 + 因果校准 + 三档方案生成。

        Args:
            reactivation_mode: True if triggered by churn-recovery feedback loop.
        """
        label = "[Step 3/4] (反馈闭环)" if reactivation_mode else "[Step 3/4]"
        print(f"\n{'─'*50}")
        print(f"{label} gap-diagnosis-engine — 保障缺口诊断与方案生成")
        print("─" * 50)

        upstream_ctx = self._output_mgr.format_context_for_agent()

        # -------------------------------------------------------------------
        # Pre-run cohort-level causal calibration (cached)
        # -------------------------------------------------------------------
        causal_context = self._prepare_gap_causal_context()

        prompt = _load_agent_prompt("gap-diagnosis-engine")
        agent = AgentRunner(prompt, self.client, model=self.model)

        if reactivation_mode:
            extra = """
**注意**: 本次诊断由流失召回(churn-recovery-agent)触发，属于「保障缺口再触达」场景。
请特别关注该用户之前流失的保单类型，在诊断报告中强调缺口紧迫性，用于唤醒用户保障意识。
"""
        else:
            extra = ""

        message = f"""{upstream_ctx}

{causal_context}

请执行保障缺口诊断的完整流程（三步走）。

**上下文信息**:
- 用户需求: {self.prompt}
- 诊断报告输出目录: {_DATA_DIR / 'reports'}
- 因果校准输出目录: {_DATA_DIR / 'causal_outputs' / 'gap_calibration'}
- 当前时间: {_now_iso()}
{extra}

请按以下顺序执行:

**Phase A — 缺口量化** (Step 3):
1. 从上游画像读取 basic_tags、insurance_tags、health_tags
2. 从上游保单状态读取最新保单数据
3. 社保商保覆盖比对：测算医疗报销缺口（自费比例、封顶线差额、目录外费用）
4. 重疾保额缺口量化：治疗费用 + 收入损失 + 康复费用模型
5. 家庭负债寿险缺口：房贷余额 + 子女教育金 + 赡养费 - 现有寿险保额
6. 四大异常识别：重复投保、保障缺失、保额不足、险种错配

**Phase B — 因果校准** (Step 4):
1. 如果尚未有该用户分群的最新因果校准参数，请调用 run_causal_analysis 进行队列级因果分析
   - 以各缺口指标为结果变量，以收入/年龄/家庭负担/城市等级为原因变量
   - 使用 DML 和 PSM 方法估计 ATE 和 CATE
2. 读取该用户所在分群的因果效应参数
3. 用因果效应权重校准缺口测算模型（如 ci_gap_multiplier、life_gap_multiplier）
4. 输出校准后的量化缺口结果

**Phase C — 方案生成** (Step 5):
1. 基于校准后的缺口数据与用户预算，生成三档家庭配置方案:
   - 极简版（刚需兜底）：医疗险 + 意外险
   - 全面版（均衡配置）：医疗 + 意外 + 重疾 + 定寿
   - 高端版（品质保障）：全面版 + 高端医疗 + 终身寿险 + 年金
2. 按刚需→升级→理财逐级推荐排序
3. 输出结构化诊断报告（JSON格式）
4. 将缺口数据推送至 churn-recovery-agent（用于缺口再触达策略）

完成后请输出诊断报告摘要和推荐优先级。"""

        result = agent.run(message)
        self.results["gap_diagnosis_engine"] = result
        if reactivation_mode:
            self.results["gap_diagnosis_reactivation"] = result
        self._output_mgr.save_output(
            "gap-diagnosis-engine", "diagnosis_result.txt", result,
            description="保障缺口诊断完整输出（社保比对/缺口量化/因果校准/三档方案/推荐排序）",
        )
        print(f"  {label} gap-diagnosis-engine 完成")

    # -----------------------------------------------------------------------
    # Steps 6-8: churn-recovery-agent
    # -----------------------------------------------------------------------

    def _step_churn_recovery_agent(self) -> None:
        """Steps 6-8: 流失检测 + 因果归因 + 差异化召回。"""
        print("\n" + "─" * 50)
        print("[Step 4/4] churn-recovery-agent — 流失识别与精准召回")
        print("─" * 50)

        upstream_ctx = self._output_mgr.format_context_for_agent()

        # -------------------------------------------------------------------
        # Pre-run cohort-level churn causal analysis (cached)
        # -------------------------------------------------------------------
        causal_context = self._prepare_churn_causal_context()

        prompt = _load_agent_prompt("churn-recovery-agent")
        agent = AgentRunner(prompt, self.client, model=self.model)

        message = f"""{upstream_ctx}

{causal_context}

请执行流失召回完整流程（三步走）。

**上下文信息**:
- 用户需求: {self.prompt}
- 流失事件输出目录: {_DATA_DIR / 'events'}
- 召回记录输出目录: {_DATA_DIR / 'recovery'}
- 效果报告输出目录: {_DATA_DIR / 'recovery'}
- 因果归因输出目录: {_DATA_DIR / 'causal_outputs' / 'churn_attribution'}
- 当前时间: {_now_iso()}

请按以下顺序执行:

**Phase A — 流失检测** (Step 6):
1. 从上游 policy-orchestrator 的事件队列中读取保单状态变更事件
2. 识别流失信号:
   - 短期险到期超过30天未续保 → expiry_no_renewal
   - 长险宽限期届满未缴费 → lapsed
   - 用户主动退保 → surrendered
3. 对每个流失事件标记：流失时间、触发保单、流失类型
4. 从上游 profile-modeler 读取该用户的画像和保单数据

**Phase B — 因果归因** (Step 7):
1. 如果尚未有该用户分群的最新流失因果归因参数，请调用 run_causal_analysis 进行队列级因果分析
   - 以「是否流失」为结果变量
   - 以保费占收入比、理赔纠纷次数、交互频次、保单数量、保障缺口总分、产品切换次数为原因变量
   - 控制年龄、收入水平、家庭结构等混杂因子
   - 使用 DML 和 PSM 估计各因素的 ATE 和 CATE
2. 基于分群因果模型 + 用户个体特征，计算各因素归因分数
3. 区分「相关性因素」与「因果性因素」，输出流失原因→因果效应强度矩阵
4. 判定主要流失原因（价格敏感型/产品不满型/需求变化型/遗忘型/理赔纠纷型）

**Phase C — 差异化召回** (Step 8):
1. 按流失类型匹配最优召回策略:
   - 价格敏感型 → 优惠券/保费折扣
   - 产品不满型 → 替代产品推荐 + 人工跟进
   - 需求变化型 → 保障缺口再触达（调用 gap-diagnosis-engine 的缺口数据）
   - 遗忘型 → 简单续保提醒 + 一键续保
   - 理赔纠纷型 → 理赔进度同步 + 人工电话
2. 如果选择「缺口再触达」策略，标记触发 gap-diagnosis-engine 反馈
3. 生成召回内容并记录召回日志
4. 设置效果跟踪（7天后检查转化状态）

完成后请输出:
- 流失用户清单及归因结果
- 推荐策略及预期转化率
- 是否触发了缺口再触达反馈
- A/B测试建议（如有多种策略可选）"""

        result = agent.run(message)
        self.results["churn_recovery_agent"] = result
        self._output_mgr.save_output(
            "churn-recovery-agent", "recovery_result.txt", result,
            description="流失召回完整输出（流失检测/因果归因/策略匹配/召回执行/效果跟踪）",
        )

        # Parse whether gap reactivation was triggered
        result_lower = result.lower()
        if any(kw in result_lower for kw in ["缺口再触达", "gap_reactivation", "触发缺口诊断", "重新诊断"]):
            self.results["_trigger_gap_reactivation"] = True

        print(f"  [Step 4] churn-recovery-agent 完成")

    # -----------------------------------------------------------------------
    # Causal inference helpers
    # -----------------------------------------------------------------------

    def _prepare_gap_causal_context(self) -> str:
        """Check for cached gap calibration causal results; run if missing.

        Returns a context string for the gap-diagnosis-engine agent message.
        """
        # Check cache
        cached = self._output_mgr.get_output(
            "gap-diagnosis-engine", "causal_gap_calibration_result.json"
        )
        if cached:
            print("  [因果层] 使用缓存的保障缺口因果校准结果")
            self.results.setdefault("_causal_runs", []).append("gap_calibration (cached)")
            return f"""## 因果推断层 — 保障缺口校准（已有缓存）

以下是最新的队列级因果分析结果，请直接用于校准缺口测算模型:

```json
{cached[:8000]}
```

如果缓存结果对应的分群参数与你当前处理的用户匹配，请直接使用其中的 calibration_params。
如果缓存已过期或用户分群不匹配，请调用 run_causal_analysis 重新分析。"""

        # Try to run causal analysis if data is available
        print("  [因果层] 未找到缓存，尝试运行保障缺口因果校准...")
        try:
            result = self._call_causal(
                trigger_name="gap_calibration",
                data_path=str(_DATA_DIR / "causal_inputs"),
                prompt=(
                    "分析用户特征对保障缺口的因果效应。"
                    "以「重疾缺口(ci_gap)」「寿险缺口(life_gap)」「医疗缺口(medical_gap)」为结果变量，"
                    "以「收入水平」「年龄」「家庭负担」「城市等级」为原因变量，"
                    "控制「是否已有该险种覆盖」作为混杂因子。"
                    "使用DML和PSM方法估计各特征的ATE和CATE。"
                    "重点关注：收入水平对重疾缺口的因果效应是否显著？"
                    "家庭负担对寿险缺口的因果效应强度如何？"
                ),
                output_subdir="gap_calibration",
                methods=["dml", "psm"],
                agent_name="gap-diagnosis-engine",
            )
            if result and "error" not in str(result).lower()[:200]:
                self.results.setdefault("_causal_runs", []).append("gap_calibration (fresh)")
                return f"""## 因果推断层 — 保障缺口校准（本次运行结果）

以下是刚完成的队列级因果分析结果:

```json
{json.dumps(result, ensure_ascii=False, indent=2, default=str)[:8000]}
```

请提取各用户分群的 calibration_params，用于校准缺口测算模型。"""
        except Exception as e:
            print(f"  [因果层] 保障缺口因果校准跳过: {e}")

        return """## 因果推断层 — 保障缺口校准

未找到缓存且无法自动运行队列因果分析。请在诊断过程中根据需要调用 run_causal_analysis 工具。
调用时以各缺口指标为结果变量，以用户特征为原因变量。"""

    def _prepare_churn_causal_context(self) -> str:
        """Check for cached churn attribution causal results; run if missing.

        Returns a context string for the churn-recovery-agent message.
        """
        cached = self._output_mgr.get_output(
            "churn-recovery-agent", "causal_churn_attribution_result.json"
        )
        if cached:
            print("  [因果层] 使用缓存的流失归因因果分析结果")
            self.results.setdefault("_causal_runs", []).append("churn_attribution (cached)")
            return f"""## 因果推断层 — 流失归因（已有缓存）

以下是最新的队列级流失因果归因结果:

```json
{cached[:8000]}
```

如果缓存的分群参数与当前流失用户匹配，请直接用于归因分数计算。
如果缓存已过期或用户分群不匹配，请调用 run_causal_analysis 重新分析。"""

        print("  [因果层] 未找到缓存，尝试运行流失归因因果分析...")
        try:
            result = self._call_causal(
                trigger_name="churn_attribution",
                data_path=str(_DATA_DIR / "causal_inputs"),
                prompt=(
                    "分析导致用户流失的因果因素。"
                    "以「是否流失(churned)」为结果变量，"
                    "以「保费占收入比」「理赔纠纷次数」「交互频次」「保单数量」「保障缺口总分」「产品切换次数」为原因变量，"
                    "以「年龄」「收入水平」「家庭结构」为混杂控制变量。"
                    "使用DML和PSM估计各因素的ATE。"
                    "重点关注：理赔纠纷对流失的因果效应是否独立于保费水平？"
                    "保障缺口分数高的用户是否更不容易流失？"
                    "输出CATE以识别不同用户分群的异质性效应。"
                ),
                output_subdir="churn_attribution",
                methods=["dml", "psm"],
                agent_name="churn-recovery-agent",
            )
            if result and "error" not in str(result).lower()[:200]:
                self.results.setdefault("_causal_runs", []).append("churn_attribution (fresh)")
                return f"""## 因果推断层 — 流失归因（本次运行结果）

以下是刚完成的队列级流失因果归因结果:

```json
{json.dumps(result, ensure_ascii=False, indent=2, default=str)[:8000]}
```

请提取各用户分群的 causal_effects 参数，用于流失归因分数计算。"""
        except Exception as e:
            print(f"  [因果层] 流失归因因果分析跳过: {e}")

        return """## 因果推断层 — 流失归因

未找到缓存且无法自动运行队列因果分析。请在归因过程中根据需要调用 run_causal_analysis 工具。
调用时以「是否流失」为结果变量，以保费占收入比、理赔纠纷等为原因变量。"""

    def _call_causal(
        self,
        trigger_name: str,
        data_path: str,
        prompt: str,
        output_subdir: str,
        methods: list[str] | None = None,
        agent_name: str = "causal",
    ) -> dict[str, Any] | None:
        """Run CausalInferencePipeline with caching.

        Results are cached both in the agent's output directory and in the
        causal_outputs data directory.
        """
        cache_key = f"causal_{trigger_name}_result.json"

        # Check cache in agent output
        cached = self._output_mgr.get_output(agent_name, cache_key)
        if cached:
            try:
                return json.loads(cached)
            except (json.JSONDecodeError, Exception):
                pass

        # Check cache in data directory
        cache_path = _DATA_DIR / "causal_outputs" / output_subdir / cache_key
        if cache_path.exists():
            try:
                return json.loads(cache_path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, Exception):
                pass

        # Run pipeline
        print(f"  [因果层] 启动 CausalInferencePipeline: {trigger_name}")
        pipeline = CausalInferencePipeline()
        causal_output_dir = str(_DATA_DIR / "causal_outputs" / output_subdir)

        try:
            result = pipeline.run(
                data_paths=data_path,
                prompt=prompt,
                client=self.client,
                model=self.model,
                output_dir=causal_output_dir,
                methods=methods,
            )

            # Cache in both locations
            result_json = json.dumps(result, ensure_ascii=False, indent=2, default=str)
            self._output_mgr.save_output(
                agent_name, cache_key, result_json,
                description=f"因果推断结果: {trigger_name}",
            )
            cache_path.parent.mkdir(parents=True, exist_ok=True)
            cache_path.write_text(result_json, encoding="utf-8")

            print(f"  [因果层] {trigger_name} 完成，结果已缓存")
            return result

        except Exception as e:
            print(f"  [因果层] {trigger_name} 执行失败: {e}")
            return {"error": str(e)}

    # -----------------------------------------------------------------------
    # Feedback logic
    # -----------------------------------------------------------------------

    def _should_trigger_gap_reactivation(self) -> bool:
        """Check whether churn-recovery-agent triggered a gap reactivation."""
        triggered = self.results.get("_trigger_gap_reactivation", False)
        if triggered:
            # Only reactivate once to avoid infinite loops
            if self.results.get("_gap_reactivation_done"):
                print("  [反馈] 缺口再触达已执行过，跳过重复触发")
                return False
            self.results["_gap_reactivation_done"] = True
            return True
        return False


# ---------------------------------------------------------------------------
# Standalone entry
# ---------------------------------------------------------------------------


def run_workflow(
    data_path: str | None = None,
    prompt: str | None = None,
    client: Any = None,
    model: str = "deepseek-v4-pro",
    output_dir: str = "./output",
) -> dict[str, Any]:
    """Convenience function: create WorkflowRunner and execute.

    Args:
        data_path: Path to input data file(s).
        prompt: User's business goal / analysis prompt.
        client: OpenAI-compatible client.
        model: Model name.
        output_dir: Directory for final output reports.

    Returns:
        Structured results dict from all workflow steps.
    """
    runner = WorkflowRunner(
        data_path=data_path,
        prompt=prompt,
        client=client,
        model=model,
        output_dir=output_dir,
    )
    return runner.run()


if __name__ == "__main__":
    import os
    from openai import OpenAI

    print("=" * 60)
    print("  personal-non-auto-insurance-agent — 独立测试运行")
    print("=" * 60)

    client = OpenAI(
        api_key=os.environ.get("DEEPSEEK_API_KEY", "sk-placeholder"),
        base_url="https://api.deepseek.com",
    )

    result = run_workflow(
        data_path="./examples/sample_data.csv",
        prompt="请为用户U20250001执行完整的保障分析：构建画像、管理保单、诊断缺口、评估流失风险。",
        client=client,
        model="deepseek-v4-pro",
        output_dir="./output",
    )

    print("\n工作流结果键:", list(result.keys()))
